### ISSUE TITLE
v1.71.0 post release improvements

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#660] opened 2024-04-30 07:49 UTC
Issues:
- [X] repo.config on sim4life was broken
- [X] networks exhaustion (sim4life simcore default network) fixed
~~panic on postgres (dalco prod / osparc-infra incidents)~~(WON'T DO)

Ideas:
* test that repo.config is valid
* monitor docker network IP space
* test docker versions are correct

_Originally posted by @YuryHrytsuk in https://github.com/ITISFoundation/osparc-simcore/issues/5619#issuecomment-2084534908_

**Comment by mrnicegyu11** [comment] 2024-05-13 11:42
Potential duplicate of https://github.com/ITISFoundation/osparc-ops-environments/issues/595

**Closed** 2024-06-12 09:51 UTC
